# Generated by Django 4.0.3 on 2022-06-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='desciption',
            new_name='description',
        ),
    ]
