# Generated by Django 4.0.3 on 2022-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_desciption_homework_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateField(),
        ),
    ]
